apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: rohitsvv/php-app:20250808_104038_12a20e3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: php-config
        env:
        - name: ENV
          value: local
        - name: MYSQL_DBPASS
          valueFrom:
            secretKeyRef:
              key: MYSQL_DBPASS
              name: php-secrets
