apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  namespace: php-app
data:
  ENV: local
  MYSQL_DBHOST: rds19may2025.cfuahjovyrht.ap-south-1.rds.amazonaws.com
  MYSQL_DATABASE: kiaar-stage
  MYSQL_DBUSER: arigel
